version: '3.8'

services:
  bot-whatsapp:
    build: .
    container_name: bot-whatsapp
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .wwebjs_auth:/usr/src/app/.wwebjs_auth # Persistir sessão do WhatsApp
      - .wwebjs_cache:/usr/src/app/.wwebjs_cache # Persistir cache
    # Healthcheck para garantir que o container está saudável
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
